// Code generated by Kitex v0.2.0. DO NOT EDIT.

package schedule

import (
	"alert/kitex_gen/api"
	"context"
	"github.com/cloudwego/kitex/client"
	"github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Schedule(ctx context.Context, req *api.ScheduleRequest, callOptions ...callopt.Option) (r *api.ScheduleResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kScheduleClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kScheduleClient struct {
	*kClient
}

func (p *kScheduleClient) Schedule(ctx context.Context, req *api.ScheduleRequest, callOptions ...callopt.Option) (r *api.ScheduleResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Schedule(ctx, req)
}
