// Code generated by Kitex v0.0.8. DO NOT EDIT.

package schedule

import (
	"alert/kitex_gen/api"
	"context"
	"github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
)

func serviceInfo() *kitex.ServiceInfo {
	return scheduleServiceInfo
}

var scheduleServiceInfo = newServiceInfo()

func newServiceInfo() *kitex.ServiceInfo {
	serviceName := "Schedule"
	handlerType := (*api.Schedule)(nil)
	methods := map[string]kitex.MethodInfo{
		"schedule": kitex.NewMethodInfo(scheduleHandler, newScheduleScheduleArgs, newScheduleScheduleResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "api",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Thrift,
		KiteXGenVersion: "v0.0.8",
		Extra:           extra,
	}
	return svcInfo
}

func scheduleHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	realArg := arg.(*api.ScheduleScheduleArgs)
	realResult := result.(*api.ScheduleScheduleResult)
	success, err := handler.(api.Schedule).Schedule(ctx, realArg.Req)
	if err != nil {
		return err
	}
	realResult.Success = success
	return nil
}
func newScheduleScheduleArgs() interface{} {
	return api.NewScheduleScheduleArgs()
}

func newScheduleScheduleResult() interface{} {
	return api.NewScheduleScheduleResult()
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Schedule(ctx context.Context, req *api.ScheduleRequest) (r *api.ScheduleResponse, err error) {
	var _args api.ScheduleScheduleArgs
	_args.Req = req
	var _result api.ScheduleScheduleResult
	if err = p.c.Call(ctx, "schedule", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
